name: Java CI/CD with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up Google Cloud credentials
        run: echo "${{ secrets.GCP_CREDENTIALS }}" > $HOME/gcp_key.json

      - name: Build with Gradle Wrapper
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp_key.json
        run: ./gradlew build

      - name: Create resources folder
        run: mkdir -p ./src/main/resources/

      - name: Create application.properties
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.properties

      - name: Build without tests
        run: ./gradlew build -x test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/reports/tests/test

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_PRIVATE_KEY }}" > ~/.ssh/gcp_key
          chmod 600 ~/.ssh/gcp_key

      - name: Copy JAR to VM
        run: scp -o StrictHostKeyChecking=no -i ~/.ssh/gcp_key build/libs/church-0.0.1-SNAPSHOT.jar mical0108@34.47.76.182:/home/mical0108/

      - name: Restart application on VM
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/gcp_key mical0108@34.47.76.182 << 'EOF'
          echo "Stopping existing application..."
          PID=$(pgrep -f 'java -jar church-0.0.1-SNAPSHOT.jar')
          if [ -n "$PID" ]; then
            kill -9 $PID
            sleep 5
            while pgrep -f 'java -jar church-0.0.1-SNAPSHOT.jar'; do
              echo "Waiting for process to terminate..."
              sleep 1
            done
          fi
          echo "Existing process terminated successfully."
          echo "Starting new application..."
          nohup java -jar /home/mical0108/church-0.0.1-SNAPSHOT.jar > /home/mical0108/nohup.out 2>&1 &
          EOF