name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up Google Cloud credentials
        run: echo "${{ secrets.GCP_CREDENTIALS }}" > $HOME/gcp_key.json

      - name: Build with Gradle Wrapper
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp_key.json
        run: ./gradlew build

      - name: Create resources folder
        run: mkdir -p ./src/main/resources/

      - name: Create application.properties
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.properties

      - name: Build without tests
        run: ./gradlew build -x test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/reports/tests/test
